// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgMbLTnkTZjx21Lw8kHn3fp4RutKBARGE',
    appId: '1:948770165877:web:63d8d277c39b9b3337143c',
    messagingSenderId: '948770165877',
    projectId: 'flutter-project-format',
    authDomain: 'flutter-project-format.firebaseapp.com',
    storageBucket: 'flutter-project-format.appspot.com',
    measurementId: 'G-9WXYRD303C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvE8X5aAQ5SUHrFkeT-9IbF4GGdmn-NTE',
    appId: '1:948770165877:android:588b4b4ab5e418f937143c',
    messagingSenderId: '948770165877',
    projectId: 'flutter-project-format',
    storageBucket: 'flutter-project-format.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOcLya1lRhxdZLoHHQfygeUWpz7Jis5Cs',
    appId: '1:948770165877:ios:5397c8dd62ccc24037143c',
    messagingSenderId: '948770165877',
    projectId: 'flutter-project-format',
    storageBucket: 'flutter-project-format.appspot.com',
    iosBundleId: 'com.flutter.project.format',
  );

}